import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landingPage/Navbar";
import Chatbot from "@/components/Chatbot";
import ReactQueryClientProvider from "@/wrappers/ReactQuery";
import { AuthProvider } from "@/context/AuthContext";
import Footer from "@/components/landingPage/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Make this async
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
            <Chatbot />
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
